# Generated by Django 4.0.5 on 2022-06-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacto_alter_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nombre'),
        ),
    ]
