# Generated by Django 4.0.5 on 2022-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_contacto_remove_producto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=50)),
                ('correoP', models.EmailField(max_length=254)),
                ('tipo_Consulta', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('aviso', models.BooleanField()),
            ],
        ),
    ]
